<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link
            rel="shortcut icon"
            href="https://freezecms.co.uk/public/emails/favicon.ico"/>
        <link
            rel="stylesheet"
            href="https://db.onlinewebfonts.com/c/a6bec1c4ef2d2fd1bac5a6951f5f32a3?family=American+Captain">
        <link
            rel="stylesheet"
            href="htttps://db.onlinewebfonts.com/c/97bc69b04c428021614d3b50c24a43ed?family=AG_Futura">
        <title>Email Template | Freeze</title>

    </head>

    @forelse()
    @endforelse


    <body style="margin: 0px;background:#131428d4;">
        <div class="wrapper">
            <script>
                var head = document.head || document.getElementsByTagName('head')[0];
                style = document.createElement('style');
                head.appendChild(style);
                style.innerHTML = "@font-face{font-family:'American_Captain';src:url(https://freezecms.co.uk/publ" +
                        "ic/emails/fonts/American_Captain/american_captain.eot),url(https://freezecms.c" +
                        "o.uk/public/emails/fonts/American_Captain/american_captain.woff2) format('woff" +
                        "2'),url(https://freezecms.co.uk/public/emails/fonts/American_Captain/american_" +
                        "captain.woff) format('woff'),url(https://freezecms.co.uk/public/emails/fonts/A" +
                        "merican_Captain/american_captain.ttf) format('truetype')}@font-face{font-famil" +
                        "y:'AG_Futura';src:url(https://freezecms.co.uk/public/emails/fonts/AG_Futura/ag" +
                        "_futura.eot),url(https://freezecms.co.uk/public/emails/fonts/AG_Futura/ag_futu" +
                        "ra.woff2) format('woff2'),url(https://freezecms.co.uk/public/emails/fonts/AG_F" +
                        "utura/ag_futura.woff) format('woff'),url(https://freezecms.co.uk/public/emails" +
                        "/fonts/AG_Futura/ag_futura.ttf) format('truetype')}@font-face{font-family:'Fut" +
                        "ura_Std';src:url(https://freezecms.co.uk/public/emails/fonts/Futura_Std/futura" +
                        "_std.eot),url(https://freezecms.co.uk/public/emails/fonts/Futura_Std/futura_st" +
                        "d.woff2) format('woff2'),url(https://freezecms.co.uk/public/emails/fonts/Futur" +
                        "a_Std/futura_std.woff) format('woff'),url(emails/fonts/Futura_Std/futura_std.t" +
                        "tf) format('truetype')}p{margin:0 0 22px}h1,h2,h3,h4,h5,h6{font-weight:400}inp" +
                        "ut::-webkit-input-placeholder{color:#fff}input:-moz-placeholder{color:#fff}inp" +
                        "ut::-moz-placeholder{color:#fff}input:-ms-input-placeholder{color:#fff}table{t" +
                        "able-layout:auto}img{max-width:calc(100% + 6px);margin:0 -3px}"
            </script>
            <table
                cellpadding="0"
                cellspacing="0"
                style="width: 100%;max-width: 100%;margin: auto;background: #ffffff;margin-bottom:-6px;"
                id="header">
                <tr>
                    <td>
                        <a
                            href="https://www.freezedebt.co.uk/"
                            style="display:block;	margin-bottom: -6px;">
                            <!-- <img src="https://freezecms.co.uk/public/emails/Freeze_E_ShotMapped1_2.jpg"
                            alt="Thanks For Registering" width="100%" style=" margin-bottom: -6px;
                            display:block;max-"> -->
                            <!-- Image Map Generated by http://www.image-map.net/ -->

                        </a>
                        <img
                            src="https://freezecms.co.uk/public/emails/thank_you_email.jpg"
                            usemap="#image-map"
                            style="display:block;margin:auto;">

                        <map name="image-map">
                            <area
                                target="_blank"
                                alt=""
                                title=""
                                href="https://www.facebook.com/FREEZEDebt"
                                coords="84,1694,15"
                                shape="circle">
                            <area
                                target="_blank"
                                alt=""
                                title=""
                                href="https://twitter.com/freeze_debt"
                                coords="151,1694,15"
                                shape="circle">
                            <area
                                target="_blank"
                                alt=""
                                title=""
                                href="https://www.instagram.com/freeze_debt/"
                                coords="216,1694,14"
                                shape="circle">
                            <area
                                target="_blank"
                                alt=""
                                title=""
                                href="https://www.freezedebt.co.uk/"
                                coords="281,1694,16"
                                shape="circle">
                            <area
                                target="_blank"
                                alt=""
                                title=""
                                href="https://go.onelink.me/app/d292015a"
                                coords="318,1675,444,1713"
                                shape="rect">
                            <area
                                target="_blank"
                                alt=""
                                title=""
                                href="https://go.onelink.me/app/d7687e0e"
                                coords="453,1675,576,1712"
                                shape="rect">
                            <area
                                target="_blank"
                                alt=""
                                title=""
                                href="https://www.freezedebt.co.uk/"
                                coords="69,36,213,85"
                                shape="rect">
                            <area
                                target="_blank"
                                alt=""
                                title=""
                                href="https://www.freezedebt.co.uk/"
                                coords="577,34,727,56"
                                shape="rect">
                        </map>
                    </td>
                </tr>
            </table>
            <!-- footer -->
            <!-- /footer -->
        </div>
    </body>

</html>